version: "3"
services:
  web:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - .:/app
    command: bash -c "nginx && ./node_modules/.bin/webpack-dev-server --content-base /app --hot --inline --port 8080"