image: docker:latest

services:
  - docker:dind

stages:
  - build
  - test

build:
  stage: build
  script:
    - docker build . -f wawa/Dockerfile
  tags:
    - docker
  
test:
  stage: test
  script:
    - docker build . -f test-cicd/Dockerfile
  tags:
    - docker